--Base simulação jornada de compras 
/**/
ALTER SESSION SET "_ORACLE_SCRIPT"= true;

---Start reset schema (comment this block to reset base, for the first run it´s not necessary)
DROP USER USR_MS_PURCHASE CASCADE;
DROP USER USR_MS_PURCHASE_PRD CASCADE;
DROP ROLE USR_MS_PURCHASE_ROLE;
DROP TABLESPACE RD_INDEX INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
---End reset schema

CREATE USER USR_MS_PURCHASE IDENTIFIED BY UsrMSJor10
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS;

CREATE USER USR_MS_PURCHASE_PRD IDENTIFIED BY oracle
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS;

CREATE ROLE USR_MS_PURCHASE_ROLE;

GRANT CREATE SESSION, CREATE TABLESPACE, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER to USR_MS_PURCHASE_ROLE;

GRANT USR_MS_PURCHASE_role TO USR_MS_PURCHASE;
GRANT USR_MS_PURCHASE_role TO USR_MS_PURCHASE_PRD;
GRANT UNLIMITED TABLESPACE TO USR_MS_PURCHASE;
GRANT UNLIMITED TABLESPACE TO USR_MS_PURCHASE_PRD;
GRANT UNLIMITED TABLESPACE TO SYSTEM;
CREATE TABLESPACE RD_INDEX
    DATAFILE 'tbsrdindex.dbf'
    SIZE 1 m
    AUTOEXTEND ON NEXT 2 m;

