GRANT SELECT ON A_RAIABD.TB_CATEGORIA TO USR_MS_JOR_CONS;
CREATE SYNONYM USR_MS_JOR_CONS.TB_CATEGORIA FOR A_RAIABD.TB_CATEGORIA;

GRANT SELECT ON A_RAIABD.TB_SUB_CATEGORIA TO USR_MS_JOR_CONS;
CREATE SYNONYM USR_MS_JOR_CONS.TB_SUB_CATEGORIA FOR A_RAIABD.TB_SUB_CATEGORIA;