
--a)    Modelo para menus 
CREATE TABLE USR_MS_PURCHASE.TB_MENU  
(CD_MENU    NUMBER(4)    NOT NULL , 
DS_MENU     VARCHAR2(50) NOT NULL , 
NM_ICONE    VARCHAR2(50), 
FL_ATIVO            NUMBER(1));

ALTER TABLE USR_MS_PURCHASE.TB_MENU ADD CONSTRAINT  
PK_TB_BF_MENU  PRIMARY KEY (CD_MENU) USING INDEX TABLESPACE RD_INDEX;

CREATE SYNONYM
 USR_MS_PURCHASE_prd.TB_MENU for USR_MS_PURCHASE.TB_MENU;

INSERT INTO USR_MS_PURCHASE.TB_MENU (CD_MENU, DS_MENU, NM_ICONE, FL_ATIVO) VALUES(1, 'Simulador de Pedidos', 'pi-sliders-h', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU (CD_MENU, DS_MENU, NM_ICONE, FL_ATIVO) VALUES(2, 'Aprovação | Envio', 'pi-user', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU (CD_MENU, DS_MENU, NM_ICONE, FL_ATIVO) VALUES(3, 'Relatórios', 'pi-file', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU (CD_MENU, DS_MENU, NM_ICONE, FL_ATIVO) VALUES(4, 'Cadastro de Parâmetros', 'pi-cog', 1);
    
CREATE TABLE USR_MS_PURCHASE.TB_MENU_ITEM  
(CD_ITEM  NUMBER(4)    NOT NULL , 
CD_MENU   NUMBER(4)    NOT NULL , 
DS_ITEM  VARCHAR2(50) NOT NULL , 
NM_URL            VARCHAR2(50) , 
NM_ICONE    VARCHAR2(50), 
FL_ATIVO          NUMBER(1));

ALTER TABLE USR_MS_PURCHASE.TB_MENU_ITEM ADD CONSTRAINT  PK_TB_MENU_ITEM  PRIMARY KEY (CD_ITEM, CD_MENU) USING INDEX TABLESPACE RD_INDEX;
ALTER TABLE USR_MS_PURCHASE.TB_MENU_ITEM ADD CONSTRAINT FK_TB_MENU_ITEM_01 FOREIGN KEY (CD_MENU) REFERENCES USR_MS_PURCHASE.TB_MENU (CD_MENU);

CREATE INDEX USR_MS_PURCHASE.IX_TB_MENU_ITEM_01 ON USR_MS_PURCHASE.TB_MENU_ITEM (CD_MENU)  tablespace RD_INDEX;

CREATE SYNONYM USR_MS_PURCHASE_prd.TB_MENU_ITEM for USR_MS_PURCHASE.TB_MENU;

INSERT INTO USR_MS_PURCHASE.TB_MENU_ITEM (CD_ITEM, CD_MENU, DS_ITEM, NM_URL, NM_ICONE, FL_ATIVO) VALUES (1, 1, 'Simular', '/simulador/simular', 'pi-sliders-h', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU_ITEM (CD_ITEM, CD_MENU, DS_ITEM, NM_URL, NM_ICONE, FL_ATIVO) VALUES (2, 1, 'Acompanhar Simulação', '/simulador/acompanhar', 'pi-list', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU_ITEM (CD_ITEM, CD_MENU, DS_ITEM, NM_URL, NM_ICONE, FL_ATIVO) VALUES (3, 2, 'Pendente de aprovação', 'alcada/pendentes', 'pi-clock', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU_ITEM (CD_ITEM, CD_MENU, DS_ITEM, NM_URL, NM_ICONE, FL_ATIVO) VALUES (4, 2, 'Aprovadas para envio', 'alcada/aprrovadas', 'pi-check-circle', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU_ITEM (CD_ITEM, CD_MENU, DS_ITEM, NM_URL, NM_ICONE, FL_ATIVO) VALUES (5, 3, 'Relatório de Vendas', '/relatorio/vendas', 'pi-dollar', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU_ITEM (CD_ITEM, CD_MENU, DS_ITEM, NM_URL, NM_ICONE, FL_ATIVO) VALUES (6, 4, 'Forecast Semanal', '/parametros/forecast/semanal', 'pi-tag', 1);
INSERT INTO USR_MS_PURCHASE.TB_MENU_ITEM (CD_ITEM, CD_MENU, DS_ITEM, NM_URL, NM_ICONE, FL_ATIVO) VALUES (7, 4, 'Forecast Mensal', '/parametros/forecast/mensal', 'pi-tags', 1);
